### PR TITLE
Added links from JtL Volume 7

### PR DESCRIPTION
**Pull request by andrew-sledge**
From here: https://finopsforengineers.substack.com/p/just-the-links-051

### CODE REVIEW

**Comment by jrstorment** [comment]
Passing this to Steve Trask to find out if this is the right path for this...@Steve, we want to experiment with a list of links that initially are just a static list (this iteration) that Netlify outputs as HTML from Andrew's markdown. Later we may want to treat them like stories and pull them in different places. Can you help with this first iteration's path? Should it be in _links or just "links" if we want it to build a page that we can link to on FODO?

**Comment by stevetrask** [comment]
@jrstorment I have adjusted this to be a page in the new structure under resources, the only snag is there is no current nav link until the other changes go live - can we merge and then await that change later this week?

**Comment by stevetrask** [comment]
@andrew-sledge apologies for the change in direction here but it makes more sense in a collection and then having the resource page loop over those pages. This will allow us to scale, I assumed slightly it was just one page. 

Would you mind having a look at the links-1.md and links-2.md under the _links folder and adding a description in the front matter at the top? (currently lorem ipsum..) This is then pulled through to the listing, as per the screenshot 

Screenshot 2021-04-21 at 23 53 05

**Comment by andrew-sledge** [comment]
Sorry @stevetrask just now seeing this comment. Does the description support markdown?

**Comment by andrew-sledge** [comment]
With this last commit added in collections description and messaging to join FFE at the bottom

**Comment by andrewnhem** [comment]
@stevetrask I know you have this on the upcoming staged version. Is this PR null then? Or does it just need some serious rebasing?

**Pull request merged**
