### PR TITLE
New capabilities structure

### PR DESCRIPTION
**Pull request by stevetrask**
PLEASE DO NOT MERGE AS WIP 

@vnm-fodo Here is the adjusted structure, happy to sync to get them filled out.

### CODE REVIEW

**Comment by vnm-fodo** [comment]
heya @stevetrask - awesome stuff - thanks for updating the structure to leverage collections.  it's worth mentioning that we should be mindful the order the Capabilities are currently being rendered until we sort out how to layout/group the Capabilities (ie) group by Domain, etc ...   - any chance we can update the collection logic to order the Capabilities so they're listed on the page like this? (see snippet below) 

in the meantime, approving this change && will leave it to you to merge

--- snippet ---  
Cost Allocation (Metadata & Hierarchy)
Data Visualization and Showback
Manage Anomalies
Manage Shared Cost
Forecasting
Budget Modeling
Workload Management & Automation
Commitment Based Discounts
Resource Utilization & Rightsizing
Unit Economics
Data Normalization
IT Asset Management
---/snippet ---

**Review by vnm-fodo — APPROVED** [review]

**Comment by vnm-fodo** [comment]
resolves #267

**Comment by stevetrask** [comment]
@vnm-fodo I believe this is ready to push live, I have adjusted it slightly since discussed. Capabilities are listed in the Domain meta and it automatically pulls the info into the Domains and Capability pages showing links to the connected materials. I have not updated Stories as yet but this can be the next step once this is live.

**Comment by vnm-fodo** [comment]
resolves #268

**Pull request merged**
