### PR TITLE
Update allocate.md

### PR DESCRIPTION
**Pull request by thebostik**
Add a brief introduction to the allocation domain

### CODE REVIEW

**Review by vnm-fodo — APPROVED** [review]
this is a solid introduction for the Allocate Domain;  approving this change with the caveat that we're in the process of updating the Framework - including all of these Domains.

**Comment by thebostik** [comment]
Hey @vnm-fodo , thanks, and understand the caveat, I just didn't want one of the domains to be left blank as I'm going to be citing them in an upcoming talk.

I see this was closed with unmerged commits, I don't believe I have the ability to re-open, if you would like to do that. Thanks!

**Comment by stevetrask** [comment]
@thebostik adjusted and merged :)

**Comment by vnm-fodo** [comment]
my bad @thebostik  - thought i merged the changes before closing the PR -  thanks for the assist here @stevetrask #high5

**Pull request merged**
